RUBBER=rubber

all:
	$(RUBBER) --pdf pldi064-subramanian.tex
	$(RUBBER) --ps  pldi064-subramanian.tex

clean:
	$(RUBBER) --pdf --clean pldi064-subramanian.tex
	$(RUBBER) --ps  --clean pldi064-subramanian.tex
